# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c533de5eeafb0b014eb21b63db1cba9d2b772b174861a0389db680579b2c096696699cb79f64705c6f6b0ea8dbc29a145f214c2e66139ec46d2facbd96d14c

test:
  secret_key_base: 00b69e57b0e7b1a37c1db9cf69ec1c1d21eae49f7bc57f7b6588fbb4bb5bb4235b3282272f745f520fe16771c6de47e2bef8672e4918c33c104240e918820209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
